package com.example.opsc_code.data.model

/**
 * Data class representing an expense category in the Budget Tracker app.
 * 
 * @property id Unique identifier for the category (auto-generated by Firestore)
 * @property name The display name of the category
 * @property userId The Firebase Auth UID of the user who created this category
 */
data class Category(
    val id: String = "",
    val name: String = "",
    val userId: String = ""
) {
    /**
     * Converts this Category to a Map for Firestore storage.
     * Note: id is not included as it's used as the document ID in Firestore.
     */
    fun toMap(): Map<String, Any> {
        return hashMapOf(
            "name" to name,
            "userId" to userId
        )
    }

    companion object {
        /**
         * Creates a Category from a Firestore document map.
         * 
         * @param id The document ID from Firestore
         * @param map The document data map
         * @return A Category object populated with the map data
         */
        fun fromMap(id: String, map: Map<String, Any>?): Category {
            return Category(
                id = id,
                name = map?.get("name") as? String ?: "",
                userId = map?.get("userId") as? String ?: ""
            )
        }
    }
}
