package com.example.opsc_code.data.model

import java.util.Date

/**
 * Data class representing an expense entry in the Budget Tracker app.
 *
 * @property id Unique identifier for the expense (auto-generated by Firestore)
 * @property userId The Firebase Auth UID of the user who created this expense
 * @property categoryId The ID of the category this expense belongs to
 * @property description Description of the expense
 * @property date Date of the expense (stored as timestamp)
 * @property startTime Start time of the expense activity
 * @property endTime End time of the expense activity
 * @property amount The monetary amount of the expense
 * @property photoUrl Optional URL to a photo of the receipt/expense
 */
data class Expense(
    val id: String = "",
    val userId: String = "",
    val categoryId: String = "",
    val description: String = "",
    val date: Date? = null,
    val startTime: String = "",
    val endTime: String = "",
    val amount: Double = 0.0,
    val photoUrl: String = ""
) {
    /**
     * Converts this Expense to a Map for Firestore storage.
     * Note: id is not included as it's used as the document ID in Firestore.
     */
    fun toMap(): Map<String, Any?> {
        return hashMapOf(
            "userId" to userId,
            "categoryId" to categoryId,
            "description" to description,
            "date" to date,
            "startTime" to startTime,
            "endTime" to endTime,
            "amount" to amount,
            "photoUrl" to photoUrl
        )
    }

    companion object {
        /**
         * Creates an Expense from a Firestore document map.
         *
         * @param id The document ID from Firestore
         * @param map The document data map
         * @return An Expense object populated with the map data
         */
        @Suppress("UNCHECKED_CAST")
        fun fromMap(id: String, map: Map<String, Any>?): Expense {
            return Expense(
                id = id,
                userId = map?.get("userId") as? String ?: "",
                categoryId = map?.get("categoryId") as? String ?: "",
                description = map?.get("description") as? String ?: "",
                date = (map?.get("date") as? com.google.firebase.Timestamp)?.toDate(),
                startTime = map?.get("startTime") as? String ?: "",
                endTime = map?.get("endTime") as? String ?: "",
                amount = (map?.get("amount") as? Number)?.toDouble() ?: 0.0,
                photoUrl = map?.get("photoUrl") as? String ?: ""
            )
        }
    }
}
